-- AlterTable
ALTER TABLE `products` ADD COLUMN `cp` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `mrp` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `sp` DECIMAL(10, 2) NOT NULL DEFAULT 0.00;
